services:
  web:
    build:
      context: app
      target: dev-envs
    ports: 
      - '80:80'
    command:
      - /bin/bash
      - -c
      - |
        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/var/www/html/